### ISSUE TITLE
When I launch Server

### ISSUE THREAD

**Issue by dansleboby** [iUltimateLP/Factorio-SimpleTeleporters#1]
2.478 Info Scenario.cpp:124: Map version 0.12.26-0
   5.419 Error MultiplayerManager.cpp:110: MultiplayerManager failed: "**SimpleTeleporters**/control.lua:3: **SimpleTeleporters**/gui.lua:234: attempt to index global 'game' (a nil value)"
   5.419 Info MultiplayerManager.cpp:906: networkTick(0) mapTick(-1) changing state from(CreatingGame) to(InitializationFailed)
   5.419 Error Main.cpp:328: Couldn't load the game for MP: **SimpleTeleporters**/control.lua:3: **SimpleTeleporters**/gui.lua:234: attempt to index global 'game' (a nil value)

**Comment by iUltimateLP** [comment]
Does this also happen in singleplayer?

**Comment by dansleboby** [comment]
Excuse me, the I have the error only on versions 0.0.4
0.0.5 it ok

I don't know if you can change the version listed on http://www.factoriomods.com/mods/simpleteleporters

Thanks

**Comment by iUltimateLP** [comment]
I added it into factoriomods.com! Thanks for your feedback!
